config/routes.rb
TaskMate::Application.routes.draw do
  root :to => 'root#index'
  resources :task_lists

  devise_for :users

  resources :tasks, :except => [:index]
  resources :task_lists, :except => [:index]

  get '/:id', :to => 'users#show', :as => :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :subject, :description, :due_at

  before_create :set_default_state

  has_many :assignments, :dependent => :delete_all

  validates :subject, :presence => true, :length => {:maximum => 255} 
  validates :description, :length => {:maximum => 1000}

  scope :current, where(:state => 'new')
  scope :completed, where(:state => 'completed')
  scope :cancelled, where(:state => 'cancelled')
  scope :expired, where(:state => 'expired')

  def new?
    state == 'new'
  end

  def cancelled?
    state == 'cancelled'
  end

  def completed?
    state == 'completed'
  end

  def expired?
    state == 'expired'
  end

  def complete!
    raise "Cannot complete cancelled task" if cancelled?
    raise "Cannot complete expired task" if expired?
    self.completed_at = DateTime.now
    self.state = 'completed'
    self.save
  end

  def cancel!
    raise "Cannot cancel completed task" if completed?
    raise "Cannot cancel expired task" if expired?
    self.state = 'cancelled'
    self.save
  end

  def expire!
    raise "Cannot exire completed task" if completed?
    raise "Cannot expire cancelled task" if cancelled?
    self.state = 'expired'
    self.save
  end

private
  
  def set_default_state
    self.state = 'new'
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/new
  # GET /tasks/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @task }
    end
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    respond_to do |format|
      if @task.save
        current_user.tasks << @task
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render json: @task, status: :created, location: @task }
      else
        format.html { render action: "new" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tasks/1
  # PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update_attributes(params[:task])
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_at %><br />
    <%= f.datetime_select :due_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/_menu.html.erb
<ul class="task-menu">
  <% if can? :destroy, task %>
    <li><%= link_to icon(:destroy), task_path(task), :method => :delete %></li>
  <% end %>
  <% if can? :update, task %>
    <li><%= link_to icon(:edit), edit_task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/_task.html.erb
<li class="task" id="<%= dom_id(task) %>">
  <h2 class="subject"><%= link_to task.subject, task %></h2>
  <%= render 'tasks/menu', :task => task %>
</li>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', user_path(current_user) %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(current_user) %>

app/views/tasks/show.html.erb
<p>
  <b>Subject:</b>
  <%= @task.subject %>
</p>

<p>
  <b>Description:</b>
  <%= @task.description %>
</p>

<p>
  <b>Due at:</b>
  <%= @task.due_at %>
</p>


<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', user_path(current_user) %>