config/routes.rb
TaskMate::Application.routes.draw do
  root :to => 'root#index'
  resources :task_lists

  devise_for :users

  resources :tasks, :except => [:index]
  resources :task_lists, :except => [:index]

  get '/:id', :to => 'users#show', :as => :user
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskMate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if Rails.env.development? %>
    <%= render 'shared/dev_menu' %>
  <% end %>
  <div id="page_wrapper" class="<%= if notice or alert then "flash" end %>">
    <header class="user">
      <span class="alias"><%= current_user.alias_name %></span>
      <span class="name">(<%= current_user.first_name %> <%= current_user.last_name %>)</span>
      <%= link_to 'Manage Account', edit_registration_path(current_user), :class => 'manage' %>
    </header>

    <header class="tasks-menu">
      <div class="new-task">
        <%= link_to 'New Task', new_task_path %>
      </div>
      <ul class="task-lists">
        <li class="my-tasks task-list">
          <%= link_to "My Tasks", user_path(current_user) %>
          <ul class="scopes">
            <li class="scope completed"><%= link_to "Completed", user_path(current_user, :scope => 'completed') %></li>
            <li class="scope cancelled"><%= link_to "Cancelled", user_path(current_user, :scope => 'cancelled') %></li>
            <li class="scope expired">  <%= link_to "Expired",   user_path(current_user, :scope => 'expired')   %></li>
          </ul>
        </li>
        <% current_user.task_lists.each do |task_list| %>
          <li id="<%= dom_id(task_list) %>" class="task-list">
            <%= link_to task_list.name, user_path(:task_list => task_list) %>
            <ul class="scopes">
              <li class="scope completed"><%= link_to "Completed", user_path(task_list, :task_list => task_list, :scope => 'completed') %></li>
              <li class="scope completed"><%= link_to "Cancelled", user_path(task_list, :task_list => task_list, :scope => 'cancelled') %></li>
              <li class="scope completed"><%= link_to "Expired",   user_path(task_list, :task_list => task_list, :scope => 'expired') %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </header>
    
    <div id="content">
      <div id="flash">
        <%=
        if notice
          content_tag :span, notice, :class => 'notice'
        elsif alert
          content_tag :span, alert, :class => 'alert'
        end
        %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskMate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="devise">
  <div id="page_wrapper">
    <%= yield %>
  </div>
</body>